### ISSUE TITLE
Need the actual game to be coded in java

### ISSUE THREAD

**Issue by PawelMilewski1** [Fm5649/ECE-366-Project#5]
im assuming this could then be connected later to the database. 

should be runnable in the terminal and i guess it can ask for the two players usernames and maybe passwords?
then the two players can play the game. so they can type "attack" or "transfer" (we can just stick to full caps/lowercase or make a function) then the target hand ("P1Hand1", P1Hand2", "P2Hand1", "P2Hand2"). 

there would then be variables for all these hands in the file. don't need to make a visual in the terminal. we can simply draw the chopstick diagram as we play on the chalkboard during presentation?

**Comment by Fm5649** [comment]
For the command line, we can make it so that the players take turns inputting their commands on the command line. So player 1 enters their command, shows the result, then prompts player 2 to type in their command. To show the score, we can just show the actual number for each hand, for example:

Player 1
Left Hand: 5          Right Hand: 5

Player 2
Left Hand: 5          Right Hand: 5

and the numbers just updates as the game goes on

**Comment by Fm5649** [comment]
We need to figure out where exactly out code for the game will be located, and make sure that the functions can be accessed through the command line
